apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocpt01-initializer-app
  namespace: argocd
spec:
  project: app-of-apps
  source:
    repoURL: https://github.com/gattma/argo-test.git
    targetRevision: app-of-apps-old
    path: appsets/ocpt01
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true