apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-demo-deployment
  labels:
    app: silly-demo
spec:
  selector:
    matchLabels:
      app: silly-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: silly-demo
    spec:
      containers:
      - name: silly-demo
        image: ghcr.io/gattma/silly-demo:main-6664d69
        ports:
        - containerPort: 8080