apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: instances
  namespace: gattma-pg
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - list:
        elements:
          - instance: nginx1
            namespace: gattma-pg
            branch: main
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "instance-{{ instance }}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        # URL of the repository
        repoURL: https://github.com/gattma/argo-test.git
        # Revision (tag/branch/commit) of the repository (eg HEAD)
        targetRevision: "{{ branch }}"
        # Path within the repository where Kubernetes manifests (and/or Helm, Kustomize, Jsonnet resources) are located
        path: argocd/instances/{{ instance }}
      destination:
        server: "{{ url }}"
        namespace: "{{ namespace }}"