kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: demo-microservice
  namespace: baukasten-argocd-test
spec:
  host: demo-microservice-baukasten-argocd-test.apps.play.gepaplexx.com
  to:
    kind: Service
    name: demo-microservice
    weight: 100
  port:
    targetPort: port-8080
  wildcardPolicy: None