# It's the same as helmApp.yml, only that we can deploy the yml file without helm
{{- range .Values.directoryApps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Values.namespaceOverwrite | default "ics-int-gitops-prod" }}
  labels:
    type: argoApp
spec:
  source:
    repoURL: {{ .source.repoURL | default $.Values.global.gitRepoUrl | quote }}
    targetRevision: {{ .source.targetRevision | quote }}
    path: {{ .source.path | quote }}
  {{- if .ignoreDifferences }}
  ignoreDifferences:
  {{ toYaml .ignoreDifferences | indent 4 }}
  {{- end }}
project: {{ .appProject | default $.Values.global.appProject | quote }}
destination:
  {{- if .destination }}
  server: {{ .destination.server | default $.Values.global.destinationServer | quote }}
  namespace: {{ .destination.namespace | default $.Values.global.destinationNamespace | quote }}
  {{- else }}
  server: {{ $.Values.global.destinationServer | default "https://kubernetes.default.svc" | quote }}
  namespace: {{ $.Values.global.destinationNamespace | quote }}
  {{- end }}
  {{- if or .syncPolicy $.Values.global.syncPolicy }}
syncPolicy:
  {{ toYaml (.syncPolicy | default $.Values.global.syncPolicy ) | indent 4 }}
  {{- end }}
...
{{- end }}