apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app-1-dev
namePrefix: dev-
commonLabels:
  stage: dev

resources:
- ../../base

patches:
- path: version.yaml
- path: replicas.yaml
