apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-
commonLabels:
  stage: prod

resources:
- ../../base

patches:
- path: version.yaml
- path: replicas.yaml
